### ISSUE TITLE
version 3.0.0 console.log in utils.js file

### ISSUE THREAD

**Issue by ptboyer** [Sitebase/react-avatar#104]
When using `react-avatar@3.0.0` a `console.log` has been left in, and it needlessly pollutes the console ([utils.js#L101](https://github.com/Sitebase/react-avatar/blob/f19e06a0bd3e172f2851b2c7c1f72dae233ca9b3/lib/utils.js#L101)).

**Comment by JorgenEvens** [comment]
Duplicate of https://github.com/Sitebase/react-avatar/issues/102

**Comment by Sitebase** [comment]
This issue is resolved in version `3.0.1`
