### ISSUE TITLE
index.d.ts

### ISSUE THREAD

**Issue by iamdanthedev** [Sitebase/react-avatar#110]
```
declare module "react-avatar" {
  export interface ReactAvatarProps {
    className?: string;
    email?: string;
    md5Email?: string;
    facebookId?: string;
    twitterHandle?: string;
    googleId?: string;
    skypeId?: string;
    name?: string;
    maxInitials?: number;
    value?: string;
    color?: string;
    fgColor?: string;
    size?: string;
    textSizeRatio?: number;
    round?: boolean | string;
    src?: string;
    style?: any;
    unstyled?: boolean;
    onClick?: (e: React.SyntheticEvent<any>) => any;
  }

  declare const ReactAvatar: React.ComponentType<ReactAvatarProps>;

  export default ReactAvatar;
}
```

**Comment by JorgenEvens** [comment]
Hi @iamdanthedev,

First of all, thanks for these type definitions 🎉 
We've recently added some additional props and a `ConfigProvider`. It would be awesome if you could add the definitions for those as well and create a PR, since neither @Sitebase or me use typescript ourselves.

**Comment by JorgenEvens** [comment]
Closing in favour of https://github.com/Sitebase/react-avatar/pull/111

**Comment by JorgenEvens** [comment]
Version [v3.1.1](https://github.com/Sitebase/react-avatar/releases/tag/v3.1.1) has been released which now includes TypeScript definitions thanks to @iamdanthedev !
