### ISSUE TITLE
react-virtualized - Can't call setState (or forceUpdate) on an unmounted component.

### ISSUE THREAD

**Issue by shauntrennery** [Sitebase/react-avatar#112]
setState error when used in a react-virtualized list or table.

in Avatar
    in withAvatarConfig (at index.js:61)
    in div (at index.js:60)
    in Avatar (at index.js:447)
    in div (created by Grid)
    in div (at index.js:19)

**Comment by JorgenEvens** [comment]
Hi @shauntrennery,

Thanks for the bug report!

This should now be fixed on the `master` branch, I will be releasing [a new version](https://github.com/Sitebase/react-avatar/milestone/19?closed=1) on NPM once https://github.com/Sitebase/react-avatar/pull/111 is ready.

**Comment by JorgenEvens** [comment]
Hi @shauntrennery,

A fix for this issue has now been released as [v3.1.1](https://github.com/Sitebase/react-avatar/pull/111) 🎉 
Thanks again for reporting this issue!

**Comment by shauntrennery** [comment]
@JorgenEvens working like a charm. Thank you.
