### ISSUE TITLE
Size 100% doesn't render the text properly

### ISSUE THREAD

**Issue by MarcoCanalcar** [Sitebase/react-avatar#121]
When you specify a size of 100%, the text inside doesn't render properly. It renders very small and not centered
I believe this is caused by:
- The division by 3 when calculating the fontSize. If you specify a percentage it is not relative to the parents height, but to the parent text-size (1em). Making the fontSize relative to the parents height looks like a very tricky problem to [solve](https://css-tricks.com/fitting-text-to-a-container/).
- The same happens with the line-height attribute. Maybe another technique for centering should be use, such as flexbox (?)

**Comment by MarcoCanalcar** [comment]
Looks like someone made a React fork of the FitText plugin which may be useful in this scenario [](http://softwarepsychonaut.com/react-fittext/)

**Comment by MarcoCanalcar** [comment]
In my opinion, a much better option would be to use svg's to render the icons. I made a couple of tests and it works flawlessly without the need to define a fixed size, just matching the parent size:

-https://codepen.io/anon/pen/oPBGNa
-https://codepen.io/anon/pen/bxgoWe

**Comment by JorgenEvens** [comment]
Sadly the SVG approach breaks down as well when we consider that not all initial have exactly two characters in them.

**Comment by JorgenEvens** [comment]
This issue has been fixed in the [v3.3.0](https://github.com/Sitebase/react-avatar/milestone/22?closed=1) release. Thanks for the bug report and the help looking for a solution!

**Comment by JorgenEvens** [comment]
After fixing this issue some more issues related to text scaling turned up, I'd love to hear the opinion of react-avatar's users on [the issue](https://github.com/Sitebase/react-avatar/pull/134).

I'm re-opening this issue so users find their way to the [PR](https://github.com/Sitebase/react-avatar/pull/134) and the origin of the current text scaling calculation.
