### ISSUE TITLE
Updated to latest version with Initial changes and Initials are broken

### ISSUE THREAD

**Issue by seandelaney** [Sitebase/react-avatar#127]
<img width="86" alt="screen shot 2018-09-14 at 11 22 16" src="https://user-images.githubusercontent.com/580403/45544893-8a0e9880-b810-11e8-8ddb-2169bc85c798.png">

My avatar component looks like:

```<Avatar className="d-none d-md-block" color="#1CA3AE" fgColor="#ffffff" name={`${firstName} ${lastName}`} round={true} size="39" />```

**Comment by JorgenEvens** [comment]
Hi @seandelaney,

So sorry that the last release broke the initials for you, could it be that `d-md-block` does something similar to `display: block !important`?

It looks like the style we put on the tag is being overwritten.

**Comment by seandelaney** [comment]
If I remove the Bootstrap classes `d-none` and `d-md-block`, the initials appear like:

<img width="166" alt="screen shot 2018-09-14 at 13 24 15" src="https://user-images.githubusercontent.com/580403/45550015-9ea75c80-b821-11e8-950f-8264f86cf1cd.png">

Very small font size though. Looking at the source code, I see:

<img width="1266" alt="screen shot 2018-09-14 at 13 25 50" src="https://user-images.githubusercontent.com/580403/45550079-c3033900-b821-11e8-8580-fab114acfe4e.png">

Not sure where the font size calculating is done. Must be within the package as I don't see any specific font sizes for the component itself.

**Comment by JorgenEvens** [comment]
I'll see what I can do ensure that the `className` is not going to be an issue anymore.

Font size is probably related to the `textSizeRatio` property set on the `Avatar`. Testing showed that you should only be seeing a difference here if you are using a percent value for `size`, which you don't appear to be using.

I'll see what I can do about these issues tonight.

**Comment by JorgenEvens** [comment]
I've added a fix for the classname issue, I am however unable to reproduce the size issue. The [closes I can get](https://codesandbox.io/s/v3lxl8xxl0) is if I intentionally set the `textSizeRatio` to `5`. 
Could you add some more info on reproducing it?

**Comment by seandelaney** [comment]
I think this is my issue: https://github.com/Sitebase/react-avatar/blob/master/src/index.js#L191

My container, which the Avatar is in, is pretty long. I'm using Flex to position the Avatar to the left-hand side of the container. If I edit the source of this library locally, remove the line that sets the font size, everything works as normal again. I see the `_scaleTextNode` method was only added 9 days ago.

**Comment by JorgenEvens** [comment]
Great, thanks for letting me know!
