### ISSUE TITLE
Text scaling issues with newest version

### ISSUE THREAD

**Issue by kinke** [Sitebase/react-avatar#133]
Hi,

we use mostly initials with 2 chars. With the new text scaling logic, the sizes vary wildly and are sometimes way too small or too large, e.g.:

![image](https://user-images.githubusercontent.com/1889215/45875165-2d265b80-bd97-11e8-9b31-398262593038.png)

We use size=24 and textSizeRatio=2 in the cases above (& newest Firefox). The top avatar's font is even huger with newest Chrome (=> `font-size: calc(159.336%)`).

**Comment by kinke** [comment]
The huge size seems to be caused by updates, where the parentNode already has some `font-size: calc(x%)`, so that its measured size isn't for its default font size (100%), and the logic breaks down.

**Comment by JorgenEvens** [comment]
The issue you described in your comment has been resolved in the [3.4.4](https://github.com/Sitebase/react-avatar/milestone/27?closed=1) release of `react-avatar`. Thanks for reporting the issue.
