### ISSUE TITLE
[Input wanted] Text Scaling

### ISSUE THREAD

**Issue by JorgenEvens** [Sitebase/react-avatar#136]
After fixing [the text scaling issue](https://github.com/Sitebase/react-avatar/issues/121) some more issues related to text scaling turned up, I'd love to hear the opinion of react-avatar's users on [a suggestion](https://github.com/Sitebase/react-avatar/pull/134) that is looking to change the current implementation.

The issue is related to how text scaling currently works where it will try to fit the initials in `avatarWidth / textSizeRatio` space, which for non monospace fonts results in wildly varying font sizes for the same amount of characters.

![screenshot 2018-09-24 23 18 34](https://user-images.githubusercontent.com/223318/45979751-4f96ce00-c050-11e8-93f9-855c95aa5d4b.png)

**Comment by kinke** [comment]
I'd like the option to disable the new text scaling, simply going with `textSizeRatio` - for us, a uniform height is more important than a uniform width - and vertical centering doesn't always work correctly, e.g., with v3.4.4:

![image](https://user-images.githubusercontent.com/1889215/46015060-911b8d80-c0d1-11e8-945e-2f7f2639469a.png)

**Comment by JorgenEvens** [comment]
@kinke Could you re-create those avatars in a [codesandbox](https://codesandbox.io/s/38wyjv6lqp) so I can test your use-case? Those `JF` avatars look like the exact problem that the text scaling was attempting to address.

**Comment by kinke** [comment]
Yes you're right, there's still an update issue. I hope this helps: https://codesandbox.io/s/o2m7qzl6z

**Comment by JorgenEvens** [comment]
So a few scaling issues have come in since changing the behaviour so I have decided 'll be reverting the behaviour of font-scaling back to the old method where we calculated a fixed value based on the configured font-value.

Current behaviour will only remain enabled for relative font-sizes such as percentages.

**Comment by JorgenEvens** [comment]
https://github.com/Sitebase/react-avatar/pull/134 should address all of these issue, closing this issue for now. Feel free to open a new issue if you feel this has not been fixed.
