### ISSUE TITLE
Avatar with email address not showing gravatar

### ISSUE THREAD

**Issue by arryanggaputra** [Sitebase/react-avatar#141]
Before, this code working and I can see my garavatar image. Today is not working like before,  and I don't know why 
```
            <Avatar
              round={true}
              name={"Arryangga"}
              email={"arryanggaputra@gmail.com"}
              size={100}
              className="img-circle mt10"
            />
```
![screen shot 2018-10-23 at 15 32 28](https://user-images.githubusercontent.com/4743772/47347159-dfc04580-d6d8-11e8-91f4-9b67be9d6bfc.jpg)

**Comment by JorgenEvens** [comment]
HI @arryanggaputra,

I'm unable to reproduce your problem, it seems to load just fine in this [reproduction](https://codesandbox.io/s/jnv6jvnq55)
