### ISSUE TITLE
Avatar with only one word and starting with 'i' overflowing

### ISSUE THREAD

**Issue by rjames1295** [Sitebase/react-avatar#143]
All other avatars with one word scale properly. Only seems to affect words starting with 'i'. Doesn't matter if lowercase/uppercase.

Bug can be seen by going to demo and typing 'I'
https://www.sitebase.be/react-avatar/

**Comment by JorgenEvens** [comment]
Related to https://github.com/Sitebase/react-avatar/issues/136

**Comment by JorgenEvens** [comment]
Resolved by https://github.com/Sitebase/react-avatar/pull/134

**Comment by JorgenEvens** [comment]
This was fixed in version [v3.5.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.5.0)!
