### ISSUE TITLE
Invariant Violation: View config not found for name span. Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by renato-bvdash** [Sitebase/react-avatar#144]
Current code:
```
<Avatar
            size="56"
            name="John Doe"
            src="https://images.samsung.com/is/image/samsung/uk-evo-plus-microsd-card-with-sd-adapter-100-mb-mc64ga-eu-frontred-63687853?$PD_GALLERY_L_JPG$"
            />
```

**Comment by JorgenEvens** [comment]
Could you add more information on where and how you are using this?

What version of React are u using?
What renderer are you using? (this package is intended for `react-dom` for now)
Could you provide us with a reproduction in [CodeSandbox](https://codesandbox.io/)?

**Comment by JorgenEvens** [comment]
This issue has been open for move than 2 months without any additional feedback. Feel free to leave a comment if more information becomes available.
