### ISSUE TITLE
Get function in cache should handle localStorage errors better

### ISSUE THREAD

**Issue by tjmabey** [Sitebase/react-avatar#147]
In cache.js, the `set` function checks if localStorage exists before attempting to set an item.

ex:
`// cache not available`
       ` if (!_hasLocalStorage)`
            `return;`

I think the get function should do the same.

Perhaps my use case isn't very common but I am using this library in a chrome extension. Some users of the extension have "Block third-party cookies and site data" enabled in Chrome which disables localStorage. Because of this I am getting the following error:
> Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document

This seems to break the avatars because localStorage isn't available but `get` still tries anyways.

Eventually I will probably try to refactor the cache.js in my own fork to use the chrome storage api instead of localStorage, but for now, its fine for me to just skip cache. 

I think that the `get` function could still benefit from additional error handling along the lines of:

ex:
`if (!_hasLocalStorage)
            return null;`

**Comment by JorgenEvens** [comment]
Resolved by #147

**Comment by JorgenEvens** [comment]
This was fixed in version [v3.5.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.5.0)!
