### ISSUE TITLE
URI based source matching

### ISSUE THREAD

**Issue by patricksimonian** [Sitebase/react-avatar#152]
I was recently tasked to build something similar to what this library is doing. This package cover' 90% of what I need for functionality however It'd be great to be able to pass in values to the `<Avatar >` without knowledge of the `sourceProps` interface and have an image be returned.  This way I can assign avatars dynamically and have no knowledge of how they need to be processed.

Example:
If you want a github avatar
`<Avatar githubHandle="..." />`

But it'd be great instead too...
`<Avatar service="github" value="..."  ...rest of props />`

To further push on this idea, what my thoughts on implementation would go beyond that by allowing for a uri based on the service.

eg:
`<Avatar uri:"github://patricksimonian?prop1=value1&prop2=value2" />`

I've currently forked this library and am playing around with it but wanted to see your thoughts on this.

**Comment by patricksimonian** [comment]
#153

**Comment by JorgenEvens** [comment]
As discussed in #153, this can easily be achieved using a higher order component. An example can be found here: https://codesandbox.io/s/xr61q134w

```jsx
import React from "react";
import Avatar from "react-avatar";
import Parser from "uri-parser";

const SOURCE_TYPE_SRC_MAPPING = {
  facebook: "facebookId",
  github: "githubHandle",
  google: "googleId",
  gravatar: "email",
  skype: "skypeId",
  icon: "icon",
  src: "src",
  instagram: "instagramId",
  vkontakte: "vkontakteId"
};

export default function UriAvatar(props) {
  const { protocol, host, queryKey } = Parser.parse(props.uri);
  const idKey = SOURCE_TYPE_SRC_MAPPING[protocol];

  const uriProps = {
    ...queryKey,
    [idKey]: host
  };

  return <Avatar {...props} {...uriProps} />;
}
```
