### ISSUE TITLE
Feature for supporting Avatar stacked list and status indicator

### ISSUE THREAD

**Issue by SoorajSethumadhavan** [Sitebase/react-avatar#154]
It would be nice to have support for stacked list of multiple users, like:
![image](https://user-images.githubusercontent.com/11325941/52910469-bb0e6000-32bd-11e9-883b-bb934f3f1867.png)
and status indicators like:
![image](https://user-images.githubusercontent.com/11325941/52910477-d24d4d80-32bd-11e9-9264-31cf296bf5aa.png)

please help me out..!

**Comment by JorgenEvens** [comment]
Hi @SoorajSethumadhavan,

I don't feel this should be added to the react-avatar component directly, but I'm open to feedback from more of our users.

In the meantime here is an example of how to create a list of stacked avatars in about 30 lines, feel free copy this into your project.

https://codesandbox.io/s/mzwwz9jw99

**Comment by JorgenEvens** [comment]
I'm closing this issue as there seems to be little interested in this apart from the original issue author.
