### ISSUE TITLE
Fallback to Initials when avatar src is undefined

### ISSUE THREAD

**Issue by Pranav-Dakshina** [Sitebase/react-avatar#156]
Assuming a case where we have:
~~~react
<Avatar name="Wim Mostmans" size="150" textSizeRatio="1.75"  src={srcFileName} />
~~~

So If `src` has valid path, it shows the image; if not, it falls back to initials

**Comment by JorgenEvens** [comment]
Hi @Pranav-Dakshina ,

That is exactly how `react-avatar` works as can be seen in the [demonstration on codesandbox](https://codesandbox.io/s/n4vvq9yxwj) that I've created for you.

If I've misunderstood the question, could you please clarify?

**Comment by Pranav-Dakshina** [comment]
Hi @JorgenEvens,
Yeah that exactly what I wanted. Sorry for the false issue. I didnt see this example in docs, so assumed that this feature doesnt exist.

Thanks for the quick response!

**Comment by JorgenEvens** [comment]
No problem. Good luck!
