### ISSUE TITLE
Fallback not working for email or MD5 that's "unknown" to Gravatar

### ISSUE THREAD

**Issue by Eric24** [Sitebase/react-avatar#157]
I'm not seeing the component fallback to name/initials if the Gravatar (based on setting email or md5email) returns a 404 (in case of an email or MD5 that's "unknown" to Gravatar). Instead, I get no avatar at all. If the email or md5email is "known" to Gravatar, then it works as expected (showing the Gravatar image).

Is the fallback to name/initials expected? If so, what might be causing this to fail?

**Comment by JorgenEvens** [comment]
The fallback is expected, as can be seen on the demo where we have a set of invalid gravatar avatars. 

Could you build a small example that is not working for you on something like [codesandbox.io](https://codesandbox.io)?

**Comment by JorgenEvens** [comment]
I'm unable to reproduce the issue you are describing. [Here is a simple reproduction](https://codesandbox.io/s/13wxj7vnzq), but that is working as expected.

**Comment by Eric24** [comment]
Yes, it looks like we're doing something wrong. I appreciate the quick response and the test case!

**Comment by seawatts** [comment]
@JorgenEvens it seems as though this isn't working again. Even in your [reproduction link](https://codesandbox.io/s/13wxj7vnzq) it does not seem to be showing the email gravatar.

**Comment by JorgenEvens** [comment]
@seawatts do note that the second hash is deliberately incorrect to show the fallback.
