### ISSUE TITLE
Skype API no longer working

### ISSUE THREAD

**Issue by Eric24** [Sitebase/react-avatar#158]
It looks like the Skype API no longer allows non-authenticated retrieval of user avatars.

**Comment by JorgenEvens** [comment]
Is this an upcoming change or would you happen to have some documentation? At this point in time the API call is still working for me.

![](https://api.skype.com/users/snevenegroj/profile/avatar)

Could you maybe provide me with a username that is not working for you?

**Comment by Eric24** [comment]
Hmmm. Interesting. I've tried with known-good Skype usernames and I only get back their default "white silhouette in blue box" image. Are you actually getting the same image you would see in Skype?

In any case, when I saw that, I did a few Google searches and just saw several mentions that the API required authentication (I did not find any official documentation to that point, so maybe it's a mistake).

For now, I'd rather not share a working Skype ID in a public forum.

**Comment by JorgenEvens** [comment]
There is a privacy setting that allows only contacts to see a profile picture. Could you verify that this is not enabled?

**Comment by Eric24** [comment]
Yep. That was it. Changing that setting makes it work. Thanks for your help!

**Comment by JorgenEvens** [comment]
No problem, good to know.
