### ISSUE TITLE
Text scaling issue font-size 0px

### ISSUE THREAD

**Issue by killerchip** [Sitebase/react-avatar#159]
After updating to v3.5.0, I'm experiencing the issue where my 'initials' avatars are empty.

They are actually rendered with `font-size: 0px`. 
This does not happen on all my pages. 
Up to now I have seen it in avatars of size  = 50.

And I'm suspecting it has to do with the 'rendering' process. As some times the same pages, show the 'initials' normally. But most of the time, after a refresh, they are empty.

Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/18270110/53888259-b1f6f000-402c-11e9-9001-0b7352e22641.png)
![image](https://user-images.githubusercontent.com/18270110/53888276-be7b4880-402c-11e9-9ade-443e04cde40d.png)

**Comment by JorgenEvens** [comment]
Reproduction: https://codesandbox.io/s/yjjv63rrkz

**Comment by JorgenEvens** [comment]
@killerchip Thank you for bringing this issue to our attention, it has been resolved in the [v3.5.1](https://github.com/Sitebase/react-avatar/releases/tag/v3.5.1) release :tada: .
