### ISSUE TITLE
Any thoughts on cache expiration?

### ISSUE THREAD

**Issue by Eric24** [Sitebase/react-avatar#161]
I realized that it's possible to create a custom cache module, but I wonder if there's any thought of developing a cache module that intelligently expires the "bad links"? Specifically, the current use of localStorage maintains the "bad link" list forever (until the user explicitly clears the cache). Since users will often add and update their external avatar images, it would be better to put a time limit on the cache.

**Comment by JorgenEvens** [comment]
Hi @Eric24,

We could definitely make the default cache more configurable, but there is no ideal default solution to this problem. I'll try to make the TTL and cache size of the default cache implementation more configurable, if you are looking for something more complex I would have to point you towards a custom cache implementation.

Determining a good time limit for everyone is not very doable, similar to the default size of cache which we've seen several issues about already as well.

Currently we assume that you'll be using several different avatars using this library which will cause the 20 item limit of the cache to push out old entries automatically as time progresses.

**Comment by Eric24** [comment]
Understood. This isn't a critical issue, but I think the user experience would be improved if there was a configurable TTL for the default cache. To your point about the size of the cache, why not make that value overrideable too? I agree that there's no way to arrive at values for either of these that will work for all use-cases, but if they are both configurable, it should cover the 80% (leaving the 20% for a custom cache module).

In my use case, I'm willing to "take the hit" of more Internet traffic to test the potentially-invalid avatar sources in exchange for more timely updating of the displayed avatar, so I would probably set the TTL to something like 24 hours.

**Comment by JorgenEvens** [comment]
Hi @Eric24,

Was the implementation found in https://github.com/Sitebase/react-avatar/pull/162 what you had in mind?

**Comment by Eric24** [comment]
Yes, exactly! Will this now be the default cache provider?

**Comment by JorgenEvens** [comment]
Yes, the default cache will now expire entries older than a week and keep up to 20 entries in memory.

These two options will be tuneable by simply creating a new instance of the default cache and passing that to react-avatar using the ConfigProvider.

**Comment by Eric24** [comment]
Perfect!

**Comment by JorgenEvens** [comment]
Hi @Eric24, I've just released [v3.6.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.6.0) which includes the improved cache implementation.
