### ISSUE TITLE
Alt tag for image

### ISSUE THREAD

**Issue by developdeez** [Sitebase/react-avatar#163]
Need a way to add the 'alt' tag for accessibility

**Comment by JorgenEvens** [comment]
Hi @developdeez,

I'm adding a property named `alt` in the next release of `react-avatar`, current the `alt` tag is already being set to the value of either the `name` or `value` property set on the Avatar.

I'll add a new comment here when the next version is released.

**Comment by JorgenEvens** [comment]
Hi @developdeez,

I've just released [v3.7.0](https://github.com/Sitebase/react-avatar/milestone/33?closed=1) which now supports the `alt` attribute described above.
