### ISSUE TITLE
Warning for componentWillReceiveProps

### ISSUE THREAD

**Issue by Valkryst** [Sitebase/react-avatar#170]
When using the latest version of React, I'm receiving the following warning in the developer console.

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Avatar

**Comment by JorgenEvens** [comment]
Thanks @Valkryst for letting us know. We still use this component in React 15, so we'll have to find an easy way to maintain both.

**Comment by amcdnl** [comment]
@JorgenEvens - Its not a 'breaking' change per-say. This would error before if you had strict mode on, now its just forced error in prep for upcoming release. If you make the change suggested, it will work on both versions and be forward ready.

**Comment by JorgenEvens** [comment]
@amcdnl I was under the impression from [what I had read](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) that the `UNSAFE_*` methods were only introduced in React release 16.3 and greater. Effectively breaking our application which is still on 15.6.

I'll see what I can do to migrate this component onto the new API or unsafe methods.

**Comment by JorgenEvens** [comment]
Hi @Valkryst, @amcdnl,

I've just released [v3.7.0](https://github.com/Sitebase/react-avatar/milestone/33?closed=1) which no longer uses the deprecated `componentWillReceiveProps` but rather does the same work in `componentDidUpdate` which works out to the same behavior. This should work in all version of `react` we previously supported, adding future version of react as well.

**Comment by Valkryst** [comment]
Hey @JorgenEvens,

Thanks for the heads-up!
