### ISSUE TITLE
Allow title attribute

### ISSUE THREAD

**Issue by mattkoch614** [Sitebase/react-avatar#175]
Is it possible to set the `title` attribute for avatars so that when users hover over them, browsers will show that text? Currently, we can use the alt tag, but not title (as far as I am aware.)

Example: computerhope.com/issues/ch001076.htm

**Comment by one89** [comment]
Hi,
just submitted a PR (#176 ) for solving this.

**Comment by JorgenEvens** [comment]
Resolved by https://github.com/Sitebase/react-avatar/pull/176 and https://github.com/Sitebase/react-avatar/pull/183.

**Comment by JorgenEvens** [comment]
The `title` attribute has been introduced in [v3.8.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.8.0), thanks @one89!
