### ISSUE TITLE
Is the googleId version working? I just see a circle with a star in it. 

### ISSUE THREAD

**Issue by Scabandari** [Sitebase/react-avatar#177]
I'd love to use this library in my project if it'll generate an avatar based on a googleId. The website providing examples show the exact same thing I'm seeing, just the green circle with a star. 

Anyone have any insight on this?

**Comment by JorgenEvens** [comment]
Hi @Scabandari ,

The Google avatar was dependend on Google+, so I think this needs some work after Google killed Google+.
Since Google+ no longer exists, out of curiosity, which ID (from which service) are you using for this?

**Comment by Scabandari** [comment]
Jorgen,

Thanks for the info. I was using OAuth2 for Google and hoping the googleId
would work with the avatars.

Ryan

**Comment by JorgenEvens** [comment]
Hi @Scabandari,

Would you happen to be in possession of such an ID that you are able to share here? I'll try and investigate our options.

**Comment by canercak** [comment]
same for me

**Comment by JorgenEvens** [comment]
If you're willing to enable [avatar-redirect](https://github.com/Sitebase/react-avatar#avatar-redirect) support you'll be getting Google support back after upgrading to [v3.9.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.0) of `react-avatar` :tada: !
