### ISSUE TITLE
className prop is applied twice

### ISSUE THREAD

**Issue by martinek** [Sitebase/react-avatar#180]
When `className` prop is used, it is applied to wrapper `div` as well as nested `div` or `img` tag (whichever is used).

**Comment by JorgenEvens** [comment]
Hi @martinek ,

Sorry that it took me this long to look into it, you're correct in that this `className` is applied twice.

However other classes are preserved and to ensure you select the correct elements within the avatar component you should use your custom `className` in conjunction with the pre-applied classes.

Examples based on a custom className set to `large-avatar`

```css
/* wrapper element */
.large-avatar.sb-avatar { /* your css */ }

/* text container */
.large-avatar.sb-avatar__text { /* your css */ }

/* image container */
.large-avatar.sb-avatar__image { /* your css */ }
```

**Comment by Ivkaa** [comment]
This is causing problems with styled-components

**Comment by JorgenEvens** [comment]
Hi @Ivkaa,

Could you elaborate a bit more on the issue? You would have full control over which component you would and would not target based on the `className` specified.

In the example above that would be `large-avatar`.

**Comment by atefBB** [comment]
@JorgenEvens You saved my day twice! Thank you!

**Comment by hmu332233** [comment]
I had the same problem, but the solution is written. Thank you. 👍 

By the way, can I know what the intention of applying className twice?
