### ISSUE TITLE
Override text-transform: uppercase

### ISSUE THREAD

**Issue by realmsoft** [Sitebase/react-avatar#185]
I'd like to override the text-transform: uppercase without overriding the entire css styling of the component. I'm passing in a direct prop of "initials" where I specify what I want the initials to be (case and all).

Adding a style={{textTransform: 'lowercase'}} in react only applies to the sb-avatar, but then is immediately overwritten with the sb-avatar__text below it with text-transform: uppercase.

We currently use styled-components, so having to change this by overwriting the entire CSS is a big chunk when it'd be nice if it was just an option that I could pass in that doesn't force the upper/lower case.

**Comment by JorgenEvens** [comment]
Hi @realmsoft,

I'll see what I can do for you here. I think it would make sense to remove it entirely since the initials behaviour can be changed using the `initials` [config option](https://github.com/sitebase/react-avatar#configprovider) rather than in CSS.

**Comment by JorgenEvens** [comment]
Hi @realmsoft,

Initials are now shown as they are returned by the `initials` generator function in [v3.9.1](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.1).
