### ISSUE TITLE
Cannot resolve core-js

### ISSUE THREAD

**Issue by donaldboulton** [Sitebase/react-avatar#187]
Gatsby Error using npm

Can't resolve 'core-js/modules/es.array.concat' in 'C:\Users\Donald Boulton\Documents\GitHub\publiuslogic\publiuslogic\node_modules\react-avatar\es\sources'

Can't resolve 'core-js/modules/ANY AND ALL MODULES IN THIS DIRECTORY' in 'C:\Users\Donald Boulton\Documents\GitHub\publiuslogic\publiuslogic\node_modules\react-avatar\es\sources'

File: node_modules\react-avatar\es\sources\Github.js

package-json-lock ile
 is calling two versions of core.js ???
`"react-avatar": {
      "version": "3.9.0",
      "resolved": "https://registry.npmjs.org/react-avatar/-/react-avatar-3.9.0.tgz",
      "integrity": "sha512-i9UR3z/Y4JhAb6WH0yaAr6noLwLVgUyp7kOMu48Plc9ch6OQ3k4aDqp+m0TrCbHAn8YfRv2BevK9gA0nIqwVbA==",
      "requires": {
        "core-js": "^3.6.1",
        "is-retina": "^1.0.3",
        "md5": "^2.0.0"
      },
      "dependencies": {
        "core-js": {
          "version": "3.6.4",
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.6.4.tgz",
          "integrity": "sha512-4paDGScNgZP2IXXilaffL9X7968RuvwlkK3xWtZRVqgd8SYNiVKRJvkFd1aqqEuPfN7E68ZHEp9hDj6lHj4Hyw=="
        }
      }`

**Comment by JorgenEvens** [comment]
Hi @donaldboulton ,

I've been able to [reproduce](https://codesandbox.io/s/solitary-silence-wysj3) the issue and will be looking into what the fix should be here.

It looks like some interaction between `react-avatar` and `gatsby` as the issue [does not occur in a plain react test](https://codesandbox.io/s/hardcore-khayyam-s8h4u).

**Comment by wdavidw** [comment]
Hi, @JorgenEvens have you made any progress ?

**Comment by JorgenEvens** [comment]
Hi @donaldboulton, @wdavidw,

This seems to be a known issue with gatsby and libraries using `core-js@3`, more [here](https://github.com/gatsbyjs/gatsby/issues/17136).

Adding the following snippet in your `gatsby-node.js` will make `react-avatar` work (see [comment](https://github.com/gatsbyjs/gatsby/issues/17136#issuecomment-554426112)).

```js
exports.onCreateWebpackConfig = ({ actions, getConfig }) => {
  const config = getConfig()
  delete config.resolve.alias["core-js"]
  actions.replaceWebpackConfig(config)
}
```

Here is a working [reproduction](https://codesandbox.io/s/solitary-silence-wysj3?fontsize=14&hidenavigation=1&theme=dark).

**Comment by donaldboulton** [comment]
Fix Works perfect 
Thank You
Donald Boulton

**Comment by wdavidw** [comment]
Same with me, thanks

**Comment by JorgenEvens** [comment]
So the fix suggested in the thread I linked does not work for `react-avatar`? Does the [reproduction](https://codesandbox.io/s/solitary-silence-wysj3?fontsize=14&hidenavigation=1&theme=dark) work for you?

The suggested fix worked for me on a fresh gatsby project.

**Comment by hijarian** [comment]
@JorgenEvens The solution provided in https://github.com/Sitebase/react-avatar/issues/187#issuecomment-587187113 did work for me *only after I added core-js@3 as an explicit dependency to the whole project*. It was an implicit dependency on gatsbyjs and on react-avatar initially. Until I added core-js as a dependency on the whole project, I have been getting the same error as described in the OP.

**Comment by JorgenEvens** [comment]
Hi @hijarian,

Thanks for the update, your comment will surely help the community out until the issue is fixed in gatsby. [[1]](https://github.com/Sitebase/react-avatar/issues/198)
