### ISSUE TITLE
Typescript: Cache isn't exported as constructor

### ISSUE THREAD

**Issue by KyorCode** [Sitebase/react-avatar#189]
Hi,

It seems that cache is only exported as an interface in your library. Could you also export the constructor?

https://github.com/Sitebase/react-avatar#cache
isn't possible in a typescript setting.

After looking into it, it seems that it got removed on the following commit: 
https://github.com/Sitebase/react-avatar/commit/7e54ccc9f667a95a861e8372f44bf2972dd1ee6d

**Comment by JorgenEvens** [comment]
Hi @KyorCode ,

Thanks for the report, I'm however not sure what the exact problem is.

Are you missing the constructor type definition in `index.d.ts` or does Typescript not support import a specific member?

It would be great if you could illustrate the problem using a quick [sandbox](https://codesandbox.io/).

**Comment by KyorCode** [comment]
https://codesandbox.io/s/funny-newton-cveq0?fontsize=14&hidenavigation=1&theme=dark

Is an example. Two things going wrong. The Cache type is kind of reserved I think for the request/response Cache type.

The second you can see if you hover over the 'AvatarCache'.

**Comment by JorgenEvens** [comment]
Hi @KyorCode ,

The `Cache` constructor was addded to the typescript definitions starting [v3.9.1](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.1). Thanks for reporting the issue!

**Comment by KyorCode** [comment]
@JorgenEvens Thank you! :)
