### ISSUE TITLE
types missing for reduction of bundle size functions

### ISSUE THREAD

**Issue by fantapop** [Sitebase/react-avatar#192]
I noticed there were no types for  `createAvatarComponent`
and the various Sources listed here:

https://www.npmjs.com/package/react-avatar#reducing-bundle-size

**Comment by JorgenEvens** [comment]
@fantapop you are completely right, I'll add them as soon as I have the time (or a PR is welcome as well).

Are you aware of any tools or methods of testing for missing types automatically as part of the test infrastructure? None of my projects or those at work use TypeScript so we often don't notice it when types are missing from `react-avatar` and I would very much like to prevent these kinds of issues popping up in the future.

**Comment by fantapop** [comment]
no big rush on this as the fallback which doesn't minimize the bundle
works.  I'm not aware of any testing tools like you've mentioned although I
highly recommend checking out typescript.  :-)

**Comment by JorgenEvens** [comment]
Hi @fantapop,

Version [v3.9.5](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.5) has been released and now includes types for the individual sources and `createAvatarComponent()`.

**Comment by fantapop** [comment]
Awesome! Thanks for you work on this
