### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by lmxcraft** [Sitebase/react-avatar#194]
I have been in version 3.7.0 for a while now, any version after that fails to build all the way

```
./node_modules/babel-runtime/core-js/symbol.js
Module not found: Error: Can't resolve 'core-js/library/fn/symbol' in '/dev/project/node_modules/babel-runtime/core-js'
````

**Comment by JorgenEvens** [comment]
Hi @lmxcraft,

Could you be running into https://github.com/Sitebase/react-avatar/issues/187 or https://github.com/Sitebase/react-avatar/issues/181?

**Comment by JorgenEvens** [comment]
The issue has been further discussed in https://github.com/Sitebase/react-avatar/issues/198, and a workaround is now available in the [readme](https://github.com/Sitebase/react-avatar#note-on-usage-in-gatsby-projects).

I'll be closing this issue for the time being, feel free to leave a comment if this does not adequately answer your question.
