### ISSUE TITLE
Enforced image src/value

### ISSUE THREAD

**Issue by inlife** [Sitebase/react-avatar#196]
Hello,

First of all, amazing package!

I was wondering, is it possible somehow to force `Avatar` to render a provided `src` (or some alternative) prop first, and only if that fails (undefined or invalid value), fall back to other available sources like github/email/initials.

Right now, `src` itself is used for fallback values, which is understandably reasonable. However, I think it would be nice to have something like high-priority `src` prop that would allow developers to use their **web resource locally uploaded avatars** and only then fallback to alternatives.

Is there a way to achieve something like that with current build, or it requires a new feature to be added?

Cheers!

**Comment by JorgenEvens** [comment]
HI @inlife,

It's possible to alter the order in which the sources are used by following the example in found in the readme under [Reducing bundle size](https://github.com/Sitebase/react-avatar#webpack-4).

The order of the `sources` array dictates the order in which the component will attempt to load from different properties.

Would the example below work for you?

[CodeSandbox example](https://codesandbox.io/s/react-avatar-source-order-y6u34)

```js
import {
  createAvatarComponent,
  SrcSource,
  GithubSource,
  GravatarSource,
  IconSource
} from "react-avatar";

const Avatar = createAvatarComponent({
  sources: [SrcSource, GithubSource, GravatarSource, IconSource]
});
```

**Comment by inlife** [comment]
Oh, that would definitely work, yes. Thank you @JorgenEvens!

Also, possibly would be a good idea to add a small mention about custom priority with a link to `reducing bundle size section` somewhere there https://github.com/Sitebase/react-avatar/blame/master/README.md#L21

**Comment by inlife** [comment]
I'm closing the issue since the question has been answered

**Comment by JorgenEvens** [comment]
You are right, this should definitely be documented better. I'll see what I can do.
