### ISSUE TITLE
withAvatarConfig has issue with next/link

### ISSUE THREAD

**Issue by ducdev** [Sitebase/react-avatar#201]
![image](https://user-images.githubusercontent.com/3524016/81580198-55812480-93d7-11ea-9279-4b35a7e567c1.png)

![image](https://user-images.githubusercontent.com/3524016/81580351-87928680-93d7-11ea-8080-171b243d366f.png)

It's OK when it's standing alone, but when I wrap it inside a `<Link />`, it's showing a warning about refs.

**Comment by JorgenEvens** [comment]
Hi @ducdev,

Looks like the fix in https://github.com/zeit/next.js/issues/10305#issuecomment-579287598 might need to be applied to `react-avatar` as well.

I'll give it a try later and report back.

**Comment by JorgenEvens** [comment]
Hi @ducdev,

I've just published version [v3.9.5](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.5) which includes the `forwardRef` fix when supported by the version of React in use.

It fixes the error on the demo page, could you let me know whether this solves the issue for you as well?

**Comment by ducdev** [comment]
Hi, it works like a charm! Good job!
