### ISSUE TITLE
Invalid Typescript Typings in v3.9.5

### ISSUE THREAD

**Issue by HarrisonSeidel** [Sitebase/react-avatar#204]
After upgrading to version 3.9.5 from 3.9.4, there appear to be invalid Typescript typings, causing a build failure in my project.

https://github.com/Sitebase/react-avatar/blob/f78370ecc337100a06a1e0190b4778407b676018/index.d.ts#L160-L161

 ```
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference
'SourceConstructor' only refers to a type, but is being used as a value here
```

For one thing, `SourceConstructor` is being assigned to a constant, which won't work as it is purely a type.

Thanks.

**Comment by JorgenEvens** [comment]
Hi @HarrisonSeidel,

Version 3.9.6 has just been released and should fix the issue. Not sure how this happened as `tslint` checks the syntax of that file and did not report any issues.
