### ISSUE TITLE
Typescript build error caused by the latest type definition

### ISSUE THREAD

**Issue by nseba** [Sitebase/react-avatar#206]
Using react-avatar v3.9.6
```
.../node_modules/react-avatar/index.d.ts
(160,1): Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
```

The problem is on line 160:

```
const AvatarRedirectSource: SourceConstructor;
```

**Comment by AlexandrShcherbakov93** [comment]
Have same issue in the same version (3.9.6)

Also have 2 other issues described below

```
node_modules/react-avatar/index.d.ts:160:1 - error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

160 const AvatarRedirectSource: SourceConstructor;
    ~~~~~

node_modules/react-avatar/index.d.ts:161:69 - error TS2304: Cannot find name 'AvatarRedirectSource'.

161 export const RedirectSource: (network: string, property: string) => AvatarRedirectSource
                                                                        ~~~~~~~~~~~~~~~~~~~~

node_modules/react-avatar/index.d.ts:169:71 - error TS2304: Cannot find name 'ReactAvatar'.

169 export const createAvatarComponent: (options: CreateAvatarOptions) => ReactAvatar;
```

**Comment by JorgenEvens** [comment]
Hi @nseba, @AlexandrShcherbakov93,

I'll be looking into this as soon as possible.
It is taking me a bit longer as I'd like to make sure that `tslint` is working as it should because it didn't complain about this one despite being part of the test suite.

**Comment by JorgenEvens** [comment]
Hi @nseba, @AlexandrShcherbakov93,

Sorry this has taken so long, I'm not a TypeScript user myself so this has been somewhat tricky to get right.

Release [3.9.7](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.7) has the type definitions fixed, let me know if you have any other issues using react-avatar.
