### ISSUE TITLE
Dynamic Avtar Initials

### ISSUE THREAD

**Issue by ShayaneB** [Sitebase/react-avatar#210]
I want the Avtar initials to change as per the logged in user.. But in this "name" is hard-coded. Please help with a solution for this.

**Comment by JorgenEvens** [comment]
Hi @ShayaneB ,

You can supply any value to the `name` property that you would like to be used as the basis for the initials.

If that does not fit your use-case you could always provide a function to the `initials` property which will allow you to customize how initials are generated.

See the example in [this condesandbox](https://codesandbox.io/s/dynamic-avatar-initials-zww85?file=/src/App.js)
