### ISSUE TITLE
Failure loading google avatar images.

### ISSUE THREAD

**Issue by forlayo** [Sitebase/react-avatar#213]
I got the avatar picture from Google login, then I am using that URL on Avatar library.

I am using it as:
`<Avatar name={user.name || user.email} src={user.picture} size={props.size} round={props.round} />`

Where user.picture is:
`https://lh3.googleusercontent.com/a-/AOh14GhPQpoU8p7dup-XNsukdZPROPc4ygZc89J4epO9sw=s96-c`

This causes loading an avatar with letters from user.name. But if I remove "=s96-c" part of the src url it works. The URL as is can be open on a browser an it works without any issues..

**Comment by JorgenEvens** [comment]
Hi @forlayo ,

I'm unable to [reproduce your issue](https://codesandbox.io/s/issue-213-8kcwx), could you set up a [codesandbox](https://codesandbox.io) example which demonstrates the issue?

**Comment by forlayo** [comment]
Hi @JorgenEvens  I am now unable to reproduce the issue following the same steps; it's just working as expected. 

Apologizes and thanks for your quick review.
