### ISSUE TITLE
Facebook Graph API: User picture breaking changes

### ISSUE THREAD

**Issue by kurenov** [Sitebase/react-avatar#215]
Based on https://developers.facebook.com/docs/graph-api/reference/v8.0/user/picture, since **October 24, 2020, an access token will be required** for all UID-based queries including user profile images as I understood.

Will the `react-avatar` library support Facebook user images after October 24, 2020? If so, what data should be provided?

**Comment by JorgenEvens** [comment]
As I understand the Facebook API you should no longer be getting `UID` user IDs from the API or login flow, but rather receive the still valid `ASID` or App-scoped user ID`. The `ASID` and `PSID` IDs will continue to work, so unless you are using really old user IDs you should remain unaffected.

The ID set on a `User` resource is definitely an `ASID` [*](https://developers.facebook.com/docs/graph-api/reference/user/#fields)

> The app user's App-Scoped User ID. This ID is unique to the app and cannot be used by other apps.

Could you maybe test some of the IDs you are using `react-avatar` with? There are instructions in the warning to see if you'll be affected.

**Comment by kurenov** [comment]
@JorgenEvens thanks for reply. Just tested with `breaking_change=profile_picture` param, and it returned expected user profile. Apparently, it should work fine without any further changes in when `ASID` is used even after October 24, 2020.

**Comment by JorgenEvens** [comment]
That's what I would have expected, I'm closing this issue for now.

Feel free to leave a comment if you do experience issues.
