### ISSUE TITLE
Random color not working

### ISSUE THREAD

**Issue by Dev-Yol** [Sitebase/react-avatar#217]
random color not working

  <Avatar  {...{
            name: `${user.firstname} ${user.lastname}`,
            className: "c-avatar-img",
            color:'orange',
            round: true,
            size: 35
          }} />

**Comment by JorgenEvens** [comment]
Hi @Dev-Yol,

You are explicitly requesting the color `orange`, to have random colors appear you should remove the `color` property.

**Comment by Dev-Yol** [comment]
> Hi @Dev-Yol,
> 
> You are explicitly requesting the color `orange`, to have random colors appear you should remove the `color` property.

even i remove the color property it still remains on one color even I refresh the page

**Comment by JorgenEvens** [comment]
Hi @Dev-Yol,

Can you provide a more complete example. Everything seems to be working fine.

You can find my reproduction on [CodeSandbox}(https://codesandbox.io/s/issue-217-nkvbp?file=/src/App.js)

**Comment by Dev-Yol** [comment]
> Hi @Dev-Yol,
> 
> Can you provide a more complete example. Everything seems to be working fine.
> 
> You can find my reproduction on [CodeSandbox}(https://codesandbox.io/s/issue-217-nkvbp?file=/src/App.js)

this will work if the name is dynamic , but if the name is static it won't work even you refresh the page

 <Avatar
        {...{
          name: `Yol Torres`,
          className: "c-avatar-img",
          round: true,
          size: 35
        }}
      />

example the code above will generate same color even you refresh the page

**Comment by Dev-Yol** [comment]
![image](https://user-images.githubusercontent.com/69956128/94501495-87830e00-0234-11eb-9e8a-234287e63d01.png)

**Comment by JorgenEvens** [comment]
@Dev-Yol ,

The color is generated based on the name supplied, this is by design as it is generally more desirable to have the same name associated with the same color each time.

If you need to change this behavior I suggest you wrap the Avatar in a component that randomly sets the `color` property.
