### ISSUE TITLE
initials function 

### ISSUE THREAD

**Issue by everAtWork** [Sitebase/react-avatar#222]
hello there, I'm stuck trying to implement the initials function to make avatars based on the first letter of name that comes from a JSON... could you please help? I've read the description but it was of little help (at least to me)

**Comment by everAtWork** [comment]
I've been looking for an example of usage of ConfigProvider with initials but could'nt find any.. I believe that's what I need.

**Comment by JorgenEvens** [comment]
Hi @everAtWork,

I'll get back to you with an example later today.

**Comment by everAtWork** [comment]
@JorgenEvens right.. 👍🏼

**Comment by JorgenEvens** [comment]
Hi @everAtWork,

Not sure where you are having issues with as the method works exactly as described in [the documentation](https://github.com/Sitebase/react-avatar#avatar): [Example](https://codesandbox.io/s/crimson-frost-dh46o?file=/src/App.js).
