### ISSUE TITLE
Unable to change src, name, or value after mounting

### ISSUE THREAD

**Issue by Ganonside** [Sitebase/react-avatar#3]
The `Avatar` component only sets `this.state.src` and `this.state.value` right before the component is mounted. This causes the component to ignore changes in `this.props.src`, `this.props.name`, and `this.props.value`.

In order to fix this issue I had to add a `componentWillReceiveProps` method so that I could check for changes in the props that are used to generate the corresponding values in state. I submitted a [pull request](https://github.com/Sitebase/react-avatar/pull/2) but I wrote the code that fixed my problem with the assumption that this was just something that was overlooked. I realize that there is a possibility that this functionality was purposely neglected, I just can't think of a scenario where that might be the case.

**Comment by Sitebase** [comment]
I've merged the PR. It was indeed something that I overlooked when writing this component. 
Thanks!
