### ISSUE TITLE
ReactAvatar do not work with "src" from the start

### ISSUE THREAD

**Issue by andresmatasuarez** [Sitebase/react-avatar#47]
Hi there! first of all, this component is great, so thank you guys for investing your time in it.

I think I may have found a bug. The following is not working for me:
```jsx
<ReactAvatar src="http://example.com/image.jpg" name={....} round={true} size={100} />
```

By looking at the code, I noticed in `componentWillReceiveProps`, that you are doing this:
```javascript
if (newProps.src !== this.props.src) nextState.src = newProps.src;
```
`newProps.src` is never different from `this.props.src` (as no there is no change in src) and so `nextState.src` is never set so `this.state.src` is always null/undefined unless there is an actual change in the `src` property.

I think the solution may be to initialize `this.state.src` to `this.props.src` inside the constructor. But maybe I am missing something. I have checked and rechecked things and I found out that the only places I actually  made ReactAvatar work were effectively whenever something provoked a change in the `src` prop. The rest of them simply didnt work.

Let me know if I can help you guys out on something to get this released as soon as possible.

**Comment by Sitebase** [comment]
This is resolved by [this PR](https://github.com/Sitebase/react-avatar/pull/48) and is released as version `2.3.0`.
