### ISSUE TITLE
FacebookId of old user not clearing when new props are passed in

### ISSUE THREAD

**Issue by bsbechtel** [Sitebase/react-avatar#49]
We have an application where you can view a user's profile, and their avatar may be pulled from Facebook, Twitter, Google, etc. If you are viewing a user who has a facebookId set, and then navigate to a user who doesn't have any profile photo set (no src, facebookId, twitterHandle, googleId, skypeId, etc), the facebookId from the previous user remains as the avatar photo. I assume this is because of an issue with the shallow rendering comparison, but am not sure. It might also occur when relying on other sources for images.

**Comment by Sitebase** [comment]
@bsbechtel What version of react avatar do you have installed?

**Comment by bsbechtel** [comment]
@Sitebase I upgraded to the latest version (2.3.0) after you merged the last outstanding PR. I thought that might fix the problem, but it didn't.
