### ISSUE TITLE
Showing initials

### ISSUE THREAD

**Issue by fgiarritiello** [Sitebase/react-avatar#50]
Hi, is there a way to limit how many letters we want to show as initials.
Example: John Smith Foo, max-initials: 2, result: JS

Thanks

**Comment by gauravshah137** [comment]
Hope this get implemented soon, Would be a good feature

**Comment by erencay** [comment]
Here is a quick fix if still needed.

```
const ValueSource = require('react-avatar/lib/sources/Value');

ValueSource.prototype.getInitials = function () {
  const name = this.props.name;
  const parts = name.split(' ');
  let initials = '';

  for(let i = 0 ; i < parts.length ; i++)
  {
      initials += parts[i].substr(0, 1).toUpperCase();
  }

  return initials.slice(0, 2);
};
```

**Comment by Sitebase** [comment]
resolved by PR https://github.com/Sitebase/react-avatar/pull/72

**Comment by everAtWork** [comment]
@Sitebase hello there, I'm stuck trying to implement the initials function to make avatars based on the first letter of name that comes from a JSON... could you please help? I've read the description but it was of little help (at least to me)
