### ISSUE TITLE
gravatar & refresh on props change

### ISSUE THREAD

**Issue by soukupl** [Sitebase/react-avatar#51]
Hi,
I have found a "bug" when I pass down the email (with valid gravatar registered). Once I did, the Avatar stops updating... 

`<UserAvatar src={this.state.user.avatar} email={this.state.user.email} name={this.state.user.realname} size={40} round={true} />`

Problem with my implementation is, that my this.state.user is update via reflux data store and the avatar is currently fixed on place and login/logout action is updating the data store and this.state.user. 

How to replicate:
1. set the this.state.user.email to valid email registered with gravatar
2. set the this.state.user.email to empty string and set this.state.user.realname to anything

Avatar image will not be changed in step 2... It will not be changed until another valid gravatar email is passed down.

Problem is, that even if I create a wrapping element and removing the email={this.state.user.email} when no email is passed (logout state), tha gravatar image is still stucked in the rendered output. :(

**Comment by seandelaney** [comment]
I have the same issue.

**Comment by JorgenEvens** [comment]
Version [3.1.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.1.0) has been released which should fix this issue 🎉
