### ISSUE TITLE
className if avatar found via fallback

### ISSUE THREAD

**Issue by benjaminathlan** [Sitebase/react-avatar#52]
In this case, I would add custom CSS depending on fallback: 

![](https://cl.ly/jVqi/Image%202017-03-13%20at%201.19.59%20AM.public.png)

Could you help ?

**Comment by Sitebase** [comment]
It would probably be a good idea to implement something in `react-avatar` that sets the current active source as `className` on the root DOM element.

**Comment by JorgenEvens** [comment]
Version [3.1.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.1.0) has been released which adds this feature 🎉
