### ISSUE TITLE
Showing '*' randomly when 'name' and 'src' are set

### ISSUE THREAD

**Issue by gauravshah137** [Sitebase/react-avatar#55]
Hello, 
First of all, great plugin.
Now to the point. I saw a similar closed issue where it was an async issue due to the way setState method works.
But i'm getting this error when the src url could not be loaded.

**Comment by sww314** [comment]
I am seeing the same issue.

**Comment by mshick** [comment]
Same here.

**Comment by rcarausu** [comment]
Same here.
What happens is that I use i18n for translations and when changing languages the component renders again but taking the default value instead of taking it from the name already supplied, so I guess it's the same problem.
Anybody found a way around this?

**Comment by riseremi** [comment]
+1

**Comment by axelg12** [comment]
Did you solve this? @gauravshah137  I'm having the same problem when the URL is not being loaded

**Comment by michaeldever** [comment]
Seeing the same issue here.

**Comment by vidrir** [comment]
I am seeing this issue when trying to fetch my image, and an error being thrown, .  While the error handler tries to accomplish a setState({src: null}), there is no callback given to the setState function, and the code keeps progressing within its current (now stale context) and starts calling the next Source before the setState has had a chance to kill the bad src link.  What happens is the avatar goes from the initials to "*" at lightening speed.  One has to debug the code and step through to witness this behavior.  I have a fix, and will be submitting a PR.

**Comment by vidrir** [comment]
Please see branch: fix-issue-55-type-error for a potential fix to this issue.  When setState is called and src is updated to null, the code just keeps going with tryNextSource, when I think it should exit early after the error has been caught, wait for the state to actually change then be rendered with the newly set state.
