### ISSUE TITLE
support relative size

### ISSUE THREAD

**Issue by zhaoyao91** [Sitebase/react-avatar#57]
now size only receives number, how to specify 100%?

**Comment by kv9991** [comment]
+1 to this topic. Please, help

**Comment by eduardodelaguila** [comment]
It would be the bomb, totally +1

**Comment by roadev** [comment]
It would be very useful to be able to set a non square avatar.
For example, `size = { height: 100, width: 200 }`
In my company's main project, we use this lib for banners (non square images!)

**Comment by MarcoCanalcar** [comment]
Is this issue fixed? When trying to set size='100%' to match parent height, the circle renders correctly but the text renders very small and is not centered on the circle

**Comment by JorgenEvens** [comment]
Hi @MarcoCanalcar, would you mind creating a new issue for this so I don't lose sight of it? I'll try to find out what is going on here over the weekend.

**Comment by MarcoCanalcar** [comment]
No problem, I am trying to find a workarround at the moment and may open a PR if I find a quick and easy fix
