### ISSUE TITLE
Warning: Failed prop type: Invalid prop `round` of type `string` supplied to `Avatar`, expected `boolean`.

### ISSUE THREAD

**Issue by firaskrichi** [Sitebase/react-avatar#58]

**Comment by firaskrichi** [comment]
how can i fix this warning plz?

**Comment by Sitebase** [comment]
The round parameter is a boolean so you should use it like this `round={true}` instead of `round="true"`.

In the example in the documentation I used the wrong syntax. I've updated the documentation.
