### ISSUE TITLE
React v15.5+ gives PropTypes deprecated warning

### ISSUE THREAD

**Issue by javorosas** [Sitebase/react-avatar#59]
With react 15.5 importing PropTypes or using React.createClass is depreciated, more information here: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Everything was working great until react version 15.4.2 which I had before.

Message on Chrome devtools console:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by danpan1** [comment]
Also have this problem

**Comment by slavik-m** [comment]
+1

**Comment by Sitebase** [comment]
Solved by https://github.com/Sitebase/react-avatar/pull/63
