### ISSUE TITLE
Accessing PropTypes via the main React package deprecation warning 

### ISSUE THREAD

**Issue by sshadmand** [Sitebase/react-avatar#65]
```lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs```

**Comment by Sitebase** [comment]
There is already a PR to solve this https://github.com/Sitebase/react-avatar/pull/63

**Comment by Sitebase** [comment]
Solved by https://github.com/Sitebase/react-avatar/pull/63
