### ISSUE TITLE
Support as optional legacy react-addons-shallow-compare dep

### ISSUE THREAD

**Issue by josx** [Sitebase/react-avatar#66]
react-addons-shalloe-compare is a legacy react code (< 0.15.3), so you can put it as optional dependencie and replace it with [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)

**Comment by sairamkrish** [comment]
having same concern. Please do the needful

**Comment by slavik-m** [comment]
+1

**Comment by loris** [comment]
+1 Cannot upgrade to `2.4.0` because of this

**Comment by javorosas** [comment]
+1 Same here. React 0.16 is around the corner and this package is the only one holding me back.
