### ISSUE TITLE
Avatar from Gravatar is not updated if once returned 404

### ISSUE THREAD

**Issue by waubau** [Sitebase/react-avatar#73]
What is your cache policy? If I onced received 404 from Gravatar and then later added a photo there I do not see it becuase you put 404 in the Local Storage. How long 404 will be there?

It would be good if I could at least turn the cache off

**Comment by vivekagr** [comment]
Hi @JorgenEvens 

It'd be awesome if we could disable the cache and set the number of items we want to cache instead of the hard-coded `20`.

**Comment by JorgenEvens** [comment]
@vivekagr I'll try some things out this weekend.

**Comment by JorgenEvens** [comment]
@vivekagr You can have a look at https://github.com/Sitebase/react-avatar/pull/106, it still needs documentation before I can merge this, but feel free to play around. All of the functionality should be there.

**Comment by JorgenEvens** [comment]
Version [3.1.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.1.0) has been released which allow you to customize the caching strategy 🎉
