### ISSUE TITLE
onClick prop warning

### ISSUE THREAD

**Issue by Drafter500** [Sitebase/react-avatar#75]
Hi, I've just updated to 2.5.0 and now I see this strange warning in the console:
`Warning: Failed prop type: Avatar: prop type `onClick` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.`

The warning stays even if I add this prop

**Comment by anlesk** [comment]
I believe there is a problem with #68 PR.
`onClick: PropTypes.function` should be `onClick: PropTypes.func`

**Comment by Sitebase** [comment]
Published a new version `2.5.1` that solves this issue.
