### ISSUE TITLE
Filter special characters for initials

### ISSUE THREAD

**Issue by rogeralsing** [Sitebase/react-avatar#81]
If you have a name like "Roger (Alsing) Johansson"  and also use maxInitials set to 3, the result will be "R(J", where "RAJ" might have made more sense.

**Comment by JorgenEvens** [comment]
Starting with [v3.4.0](https://github.com/Sitebase/react-avatar/milestone/23?closed=1) you can customize what initials are shown by setting the [initials](https://github.com/Sitebase/react-avatar#avatar-1) property on either the `ConfigProvider` or the `Avatar` component.
