### ISSUE TITLE
Mistake in Documentation

### ISSUE THREAD

**Issue by SumukhaKV** [Sitebase/react-avatar#89]
In documentation, the size of the avatar is given as a string. But, when that is given as string, react throws a warning saying "expecting a number". The size works properly when the number is given in curly braces.

**Comment by FranRom** [comment]
Thanks, I realised if you put size as a string, the component take this as " line-heigth"

**Comment by JorgenEvens** [comment]
As part of https://github.com/Sitebase/react-avatar/pull/94 we've updated this property (and the documentation) to accept any valid [length](https://developer.mozilla.org/en-US/docs/Web/CSS/length) as value.
