### ISSUE TITLE
Any good alternative to this component?

### ISSUE THREAD

**Issue by javorosas** [Sitebase/react-avatar#92]
Since there's little or null (or maybe undefined, idk) interest from the repo's owner on maintaining this, it would be nice if we could share some alternatives here. Or maybe start making our own. Who's with me on this?

**Comment by benoj** [comment]
If you fork it, they will come.

**Comment by Sitebase** [comment]
Let me know if someone is interested in helping to maintain/manage this component. My free time to work/maintain this is pretty limited at the moment. If someone is interested I will give you to necessary rights on this repo.

**Comment by javorosas** [comment]
I'm interested. Let's do it.

**Comment by FranRom** [comment]
We would need to merge pending PR's please...

**Comment by benoj** [comment]
+1 to a maintainer, happy to throw my hat in also

**Comment by JorgenEvens** [comment]
I've resolved all of the pending PRs and @Sitebase will be releasing a new version within the next few days 🎉 .

Thanks for supporting this project and volunteering as maintainers, it is very much appreciated!

**Comment by Sitebase** [comment]
New version of `react-avatar` is released as version `3.0.0`.
